### ISSUE TITLE
I think you should point out the presence of soundness issues in the documentation.

### ISSUE THREAD

**Issue by steffahn** [bluss/debugit#2]
E.g.
````rs
use std::fmt;

fn foo<T>(x: T) {
    debugit::debugit!("", x);
}

fn main() {
    use std::cell::RefCell;
    struct Struct<S>(RefCell<S>);
    impl<'a> fmt::Debug for Struct<(&mut &'a str, &'a str)> {
        fn fmt(&self, _: &mut fmt::Formatter<'_>) -> fmt::Result {
            let mut this = self.0.borrow_mut();
            *this.0 = this.1;
            Ok(())
        }
    }
    let mut s = "";
    {
        let x = "Hello World!".to_owned();
        foo(Struct(RefCell::new((&mut s, x.as_str()))));
    }
    println!("{}", s); // outputs like "�B�" indicate using the String after its dropped
}
````

**Comment by bluss** [comment]
There is no active development. I think the soundness issues belong to Rust here and not the crate. But yes, some note seems to be needed. This is not something we knew when this was written.

**Comment by bluss** [comment]
Fixed in 0.2.0. Given the cadence of updates to the crate, there aren't too much details in the docs. Rust should change faster than the docs... Hopefully    (But: feature(specialization) has worked the same for four years, and the same soundness issue was there all along! It took some years before it was really noticed, though).

**Comment by steffahn** [comment]
I wasn't expecting any details in the docs, just no mention of soundness issues at all felt wrong. I guess making it `unsafe` to use was an option, too. On a related note, the release of a new version also means more readable online documentation (with dark theme available, etc.) 😃

**Comment by bluss** [comment]
Heh, it's unfortunate but unavoidable that using an old colorscheme dates the crate, like the 0.1.2 version had the vaguely carrot-red structs.

**Comment by bluss** [comment]
The crate went nightly-only with this too, so I'm really taking the axe to it :) I don't even want to update it, but figured it's very quick to do and it might become useful again for some debugging situation in the future.

**Comment by steffahn** [comment]
It can certainly be immensely useful to debug your code by switching to nightly, adding a single dependency and using a macro as opposed to temporary having to add `T: Debug` bounds to all of your functions, or other tedious refactoring. If it's not supposed to be used in production, those _incredibly_ hard-to-hit soundness issues are entirely irrelevant, it's just a temporary development tool in order to understand and fix a misbehaving program.

I suppose, nightly-only is a good thing, possibly even more of a feature than a shortcoming: that way nobody can forget to remove the dependency again after debugging is done.
